<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{

    public function run(): void
    {

        $countries = [
            ['code'=>'AA','iso'=>'AW','tld'=>'.aw','name_en'=>'Aruba','name_fa'=>'آروبا'],
            ['code'=>'AC','iso'=>'AG','tld'=>'.ag','name_en'=>'Antigua and Barbuda','name_fa'=>'آنتیگوا و باربودا'],
            ['code'=>'AE','iso'=>'AE','tld'=>'.ae','name_en'=>'United Arab Emirates','name_fa'=>'امارات متحده عربی'],
            ['code'=>'AF','iso'=>'AF','tld'=>'.af','name_en'=>'Afghanistan','name_fa'=>'افغانستان'],
            ['code'=>'AG','iso'=>'DZ','tld'=>'.dz','name_en'=>'Algeria','name_fa'=>'الجزایر'],
            ['code'=>'AJ','iso'=>'AZ','tld'=>'.az','name_en'=>'Azerbaijan','name_fa'=>'آذربایجان'],
            ['code'=>'AL','iso'=>'AL','tld'=>'.al','name_en'=>'Albania','name_fa'=>'آلبانی'],
            ['code'=>'AM','iso'=>'AM','tld'=>'.am','name_en'=>'Armenia','name_fa'=>'ارمنستان'],
            ['code'=>'AN','iso'=>'AD','tld'=>'.ad','name_en'=>'Andorra','name_fa'=>'آندورا'],
            ['code'=>'AO','iso'=>'AO','tld'=>'.ao','name_en'=>'Angola','name_fa'=>'آنگولا'],
            ['code'=>'AQ','iso'=>'AS','tld'=>'.as','name_en'=>'American Samoa','name_fa'=>'ساموای آمریکایی'],
            ['code'=>'AR','iso'=>'AR','tld'=>'.ar','name_en'=>'Argentina','name_fa'=>'آرژانتین'],
            ['code'=>'AS','iso'=>'AU','tld'=>'.au','name_en'=>'Australia','name_fa'=>'استرالیا'],
            ['code'=>'AT','iso'=>'-','tld'=>'-','name_en'=>'Ashmore and Cartier Islands','name_fa'=>'اشکمور و جزایر کارتیه'],
            ['code'=>'AU','iso'=>'AT','tld'=>'.at','name_en'=>'Austria','name_fa'=>'اتریش'],
            ['code'=>'AV','iso'=>'AI','tld'=>'.ai','name_en'=>'Anguilla','name_fa'=>'آنگویلا'],
            ['code'=>'AX','iso'=>'AX','tld'=>'.ax','name_en'=>'Åland Islands','name_fa'=>'جزایر الند'],
            ['code'=>'AY','iso'=>'AQ','tld'=>'.aq','name_en'=>'Antarctica','name_fa'=>'قطب جنوب'],
            ['code'=>'BA','iso'=>'BH','tld'=>'.bh','name_en'=>'Bahrain','name_fa'=>'بحرین'],
            ['code'=>'BB','iso'=>'BB','tld'=>'.bb','name_en'=>'Barbados','name_fa'=>'باربادوس'],
            ['code'=>'BC','iso'=>'BW','tld'=>'.bw','name_en'=>'Botswana','name_fa'=>'بوتسوانا'],
            ['code'=>'BD','iso'=>'BM','tld'=>'.bm','name_en'=>'Bermuda','name_fa'=>'برمودا'],
            ['code'=>'BE','iso'=>'BE','tld'=>'.be','name_en'=>'Belgium','name_fa'=>'بلژیک'],
            ['code'=>'BF','iso'=>'BS','tld'=>'.bs','name_en'=>'Bahamas, The','name_fa'=>'باهاما، The'],
            ['code'=>'BG','iso'=>'BD','tld'=>'.bd','name_en'=>'Bangladesh','name_fa'=>'بنگلادش'],
            ['code'=>'BH','iso'=>'BZ','tld'=>'.bz','name_en'=>'Belize','name_fa'=>'بلیز'],
            ['code'=>'BK','iso'=>'BA','tld'=>'.ba','name_en'=>'Bosnia and Herzegovina','name_fa'=>'بوسنی و هرزگوین'],
            ['code'=>'BL','iso'=>'BO','tld'=>'.bo','name_en'=>'Bolivia','name_fa'=>'بولیوی'],
            ['code'=>'BM','iso'=>'MM','tld'=>'.mm','name_en'=>'Myanmar','name_fa'=>'میانمار'],
            ['code'=>'BN','iso'=>'BJ','tld'=>'.bj','name_en'=>'Benin','name_fa'=>'بنین'],
            ['code'=>'BO','iso'=>'BY','tld'=>'.by','name_en'=>'Belarus','name_fa'=>'بلاروس'],
            ['code'=>'BP','iso'=>'SB','tld'=>'.sb','name_en'=>'Solomon Islands','name_fa'=>'جزایر سلیمان'],
            ['code'=>'BQ','iso'=>'-','tld'=>'-','name_en'=>'Navassa Island','name_fa'=>'جزیره ناواسا'],
            ['code'=>'BR','iso'=>'BR','tld'=>'.br','name_en'=>'Brazil','name_fa'=>'برزیل'],
            ['code'=>'BS','iso'=>'-','tld'=>'-','name_en'=>'Bassas da India','name_fa'=>'باساس دا هند'],
            ['code'=>'BT','iso'=>'BT','tld'=>'.bt','name_en'=>'Bhutan','name_fa'=>'بوتان'],
            ['code'=>'BU','iso'=>'BG','tld'=>'.bg','name_en'=>'Bulgaria','name_fa'=>'بلغارستان'],
            ['code'=>'BV','iso'=>'BV','tld'=>'.bv','name_en'=>'Bouvet Island','name_fa'=>'جزیره Bouvet'],
            ['code'=>'BX','iso'=>'BN','tld'=>'.bn','name_en'=>'Brunei','name_fa'=>'برونئی'],
            ['code'=>'BY','iso'=>'BI','tld'=>'.bi','name_en'=>'Burundi','name_fa'=>'بوروندی'],
            ['code'=>'CA','iso'=>'CA','tld'=>'.ca','name_en'=>'Canada','name_fa'=>'کانادا'],
            ['code'=>'CB','iso'=>'KH','tld'=>'.kh','name_en'=>'Cambodia','name_fa'=>'کامبوج'],
            ['code'=>'CD','iso'=>'TD','tld'=>'.td','name_en'=>'Chad','name_fa'=>'چاد'],
            ['code'=>'CE','iso'=>'LK','tld'=>'.lk','name_en'=>'Sri Lanka','name_fa'=>'سری لانکا'],
            ['code'=>'CF','iso'=>'CG','tld'=>'.cg','name_en'=>'Congo, Republic of the','name_fa'=>'کنگو، جمهوری'],
            ['code'=>'CG','iso'=>'CD','tld'=>'.cd','name_en'=>'Congo, Democratic Republic of the','name_fa'=>'کنگو، جمهوری دموکراتیک'],
            ['code'=>'CH','iso'=>'CN','tld'=>'.cn','name_en'=>'China','name_fa'=>'چين'],
            ['code'=>'CI','iso'=>'CL','tld'=>'.cl','name_en'=>'Chile','name_fa'=>'شیلی'],
            ['code'=>'CJ','iso'=>'KY','tld'=>'.ky','name_en'=>'Cayman Islands','name_fa'=>'جزایر کیمن'],
            ['code'=>'CK','iso'=>'CC','tld'=>'.cc','name_en'=>'Cocos (Keeling) Islands','name_fa'=>'جزایر کوکوس (کایلینگ)'],
            ['code'=>'CM','iso'=>'CM','tld'=>'.cm','name_en'=>'Cameroon','name_fa'=>'کامرون'],
            ['code'=>'CN','iso'=>'KM','tld'=>'.km','name_en'=>'Comoros','name_fa'=>'کومور'],
            ['code'=>'CO','iso'=>'CO','tld'=>'.co','name_en'=>'Colombia','name_fa'=>'کلمبیا'],
            ['code'=>'CQ','iso'=>'MP','tld'=>'.mp','name_en'=>'Northern Mariana Islands','name_fa'=>'جزایر ماریانای شمالی'],
            ['code'=>'CR','iso'=>'-','tld'=>'-','name_en'=>'Coral Sea Islands','name_fa'=>'جزایر دریای مرجانی'],
            ['code'=>'CS','iso'=>'CR','tld'=>'.cr','name_en'=>'Costa Rica','name_fa'=>'کاستاریکا'],
            ['code'=>'CT','iso'=>'CF','tld'=>'.cf','name_en'=>'Central African Republic','name_fa'=>'جمهوری آفریقای مرکزی'],
            ['code'=>'CU','iso'=>'CU','tld'=>'.cu','name_en'=>'Cuba','name_fa'=>'کوبا'],
            ['code'=>'CV','iso'=>'CV','tld'=>'.cv','name_en'=>'Cape Verde','name_fa'=>'کیپ ورد'],
            ['code'=>'CW','iso'=>'CK','tld'=>'.ck','name_en'=>'Cook Islands','name_fa'=>'جزایر کوک'],
            ['code'=>'CY','iso'=>'CY','tld'=>'.cy','name_en'=>'Cyprus','name_fa'=>'قبرس'],
            ['code'=>'DA','iso'=>'DK','tld'=>'.dk','name_en'=>'Denmark','name_fa'=>'دانمارک'],
            ['code'=>'DJ','iso'=>'DJ','tld'=>'.dj','name_en'=>'Djibouti','name_fa'=>'جیبوتی'],
            ['code'=>'DO','iso'=>'DM','tld'=>'.dm','name_en'=>'Dominica','name_fa'=>'دومینیکا'],
            ['code'=>'DQ','iso'=>'UM','tld'=>'-','name_en'=>'Jarvis Island','name_fa'=>'جزیره جارویس'],
            ['code'=>'DR','iso'=>'DO','tld'=>'.do','name_en'=>'Dominican Republic','name_fa'=>'جمهوری دومینیکن'],
            ['code'=>'DX','iso'=>'-','tld'=>'-','name_en'=>'Dhekelia Sovereign Base Area','name_fa'=>'منطقه ممنوعه Dhekelia'],
            ['code'=>'EC','iso'=>'EC','tld'=>'.ec','name_en'=>'Ecuador','name_fa'=>'اکوادور'],
            ['code'=>'EG','iso'=>'EG','tld'=>'.eg','name_en'=>'Egypt','name_fa'=>'مصر'],
            ['code'=>'EI','iso'=>'IE','tld'=>'.ie','name_en'=>'Ireland','name_fa'=>'ایرلند'],
            ['code'=>'EK','iso'=>'GQ','tld'=>'.gq','name_en'=>'Equatorial Guinea','name_fa'=>'گینه استوایی'],
            ['code'=>'EN','iso'=>'EE','tld'=>'.ee','name_en'=>'Estonia','name_fa'=>'استونی'],
            ['code'=>'ER','iso'=>'ER','tld'=>'.er','name_en'=>'Eritrea','name_fa'=>'اریتره'],
            ['code'=>'ES','iso'=>'SV','tld'=>'.sv','name_en'=>'El Salvador','name_fa'=>'السالوادور'],
            ['code'=>'ET','iso'=>'ET','tld'=>'.et','name_en'=>'Ethiopia','name_fa'=>'اتیوپی'],
            ['code'=>'EU','iso'=>'-','tld'=>'-','name_en'=>'Europa Island','name_fa'=>'جزیره اروپا'],
            ['code'=>'EZ','iso'=>'CZ','tld'=>'.cz','name_en'=>'Czech Republic','name_fa'=>'جمهوری چک'],
            ['code'=>'FG','iso'=>'GF','tld'=>'.gf','name_en'=>'French Guiana','name_fa'=>'گویان فرانسه'],
            ['code'=>'FI','iso'=>'FI','tld'=>'.fi','name_en'=>'Finland','name_fa'=>'فنلاند'],
            ['code'=>'FJ','iso'=>'FJ','tld'=>'.fj','name_en'=>'Fiji','name_fa'=>'فیجی'],
            ['code'=>'FK','iso'=>'FK','tld'=>'.fk','name_en'=>'Falkland Islands (Islas Malvinas)','name_fa'=>'جزایر فالکلند (جزایر مالویناس)'],
            ['code'=>'FM','iso'=>'FM','tld'=>'.fm','name_en'=>'Micronesia, Federated States of','name_fa'=>'میکرونزی، ایالات فدرال'],
            ['code'=>'FO','iso'=>'FO','tld'=>'.fo','name_en'=>'Faroe Islands','name_fa'=>'جزایر فارو'],
            ['code'=>'FP','iso'=>'PF','tld'=>'.pf','name_en'=>'French Polynesia','name_fa'=>'پلینزی فرانسه'],
            ['code'=>'FQ','iso'=>'UM','tld'=>'-','name_en'=>'Baker Island','name_fa'=>'جزیره بیکر'],
            ['code'=>'FR','iso'=>'FR','tld'=>'.fr','name_en'=>'France','name_fa'=>'فرانسه'],
            ['code'=>'FS','iso'=>'TF','tld'=>'.tf','name_en'=>'French Southern and Antarctic Lands','name_fa'=>'زمینهای جنوب و جنوب قطب جنوب فرانسه'],
            ['code'=>'GA','iso'=>'GM','tld'=>'.gm','name_en'=>'Gambia, The','name_fa'=>'گامبیا، The'],
            ['code'=>'GB','iso'=>'GA','tld'=>'.ga','name_en'=>'Gabon','name_fa'=>'گابن'],
            ['code'=>'GG','iso'=>'GE','tld'=>'.ge','name_en'=>'Georgia','name_fa'=>'جورجیا'],
            ['code'=>'GH','iso'=>'GH','tld'=>'.gh','name_en'=>'Ghana','name_fa'=>'غنا'],
            ['code'=>'GI','iso'=>'GI','tld'=>'.gi','name_en'=>'Gibraltar','name_fa'=>'جبل الطارق'],
            ['code'=>'GJ','iso'=>'GD','tld'=>'.gd','name_en'=>'Grenada','name_fa'=>'گرانادا'],
            ['code'=>'GK','iso'=>'-','tld'=>'.gg','name_en'=>'Guernsey','name_fa'=>'گورنسی'],
            ['code'=>'GL','iso'=>'GL','tld'=>'.gl','name_en'=>'Greenland','name_fa'=>'گرینلند'],
            ['code'=>'GM','iso'=>'DE','tld'=>'.de','name_en'=>'Germany','name_fa'=>'آلمان'],
            ['code'=>'GO','iso'=>'-','tld'=>'-','name_en'=>'Glorioso Islands','name_fa'=>'جزایر گلوریوزو'],
            ['code'=>'GP','iso'=>'GP','tld'=>'.gp','name_en'=>'Guadeloupe','name_fa'=>'گوادلوپ'],
            ['code'=>'GQ','iso'=>'GU','tld'=>'.gu','name_en'=>'Guam','name_fa'=>'گوام'],
            ['code'=>'GR','iso'=>'GR','tld'=>'.gr','name_en'=>'Greece','name_fa'=>'یونان'],
            ['code'=>'GT','iso'=>'GT','tld'=>'.gt','name_en'=>'Guatemala','name_fa'=>'گواتمالا'],
            ['code'=>'GV','iso'=>'GN','tld'=>'.gn','name_en'=>'Guinea','name_fa'=>'گینه'],
            ['code'=>'GY','iso'=>'GY','tld'=>'.gy','name_en'=>'Guyana','name_fa'=>'گایانا'],
            ['code'=>'GZ','iso'=>'-','tld'=>'-','name_en'=>'Gaza Strip','name_fa'=>'نوار غزه'],
            ['code'=>'HA','iso'=>'HT','tld'=>'.ht','name_en'=>'Haiti','name_fa'=>'هائیتی'],
            ['code'=>'HK','iso'=>'HK','tld'=>'.hk','name_en'=>'Hong Kong','name_fa'=>'هنگ کنگ'],
            ['code'=>'HM','iso'=>'HM','tld'=>'.hm','name_en'=>'Heard Island and McDonald Islands','name_fa'=>'جزایر هرد و جزایر مک دونالد'],
            ['code'=>'HO','iso'=>'HN','tld'=>'.hn','name_en'=>'Honduras','name_fa'=>'هندوراس'],
            ['code'=>'HQ','iso'=>'UM','tld'=>'-','name_en'=>'Howland Island','name_fa'=>'جزیره Howland'],
            ['code'=>'HR','iso'=>'HR','tld'=>'.hr','name_en'=>'Croatia','name_fa'=>'کرواسی'],
            ['code'=>'HU','iso'=>'HU','tld'=>'.hu','name_en'=>'Hungary','name_fa'=>'مجارستان'],
            ['code'=>'IC','iso'=>'IS','tld'=>'.is','name_en'=>'Iceland','name_fa'=>'ایسلند'],
            ['code'=>'ID','iso'=>'ID','tld'=>'.id','name_en'=>'Indonesia','name_fa'=>'اندونزی'],
            ['code'=>'IM','iso'=>'IM','tld'=>'.im','name_en'=>'Isle of Man','name_fa'=>'جزیره من'],
            ['code'=>'IN','iso'=>'IN','tld'=>'.in','name_en'=>'India','name_fa'=>'هندوستان'],
            ['code'=>'IO','iso'=>'IO','tld'=>'.io','name_en'=>'British Indian Ocean Territory','name_fa'=>'قلمرو اقیانوس هند بریتانیا'],
            ['code'=>'IP','iso'=>'-','tld'=>'-','name_en'=>'Clipperton Island','name_fa'=>'جزیره Clipperton'],
            ['code'=>'IR','iso'=>'IR','tld'=>'.ir','name_en'=>'Iran','name_fa'=>'ایران'],
            ['code'=>'IS','iso'=>'IL','tld'=>'.il','name_en'=>'Israel','name_fa'=>'اسرائيل'],
            ['code'=>'IT','iso'=>'IT','tld'=>'.it','name_en'=>'Italy','name_fa'=>'ایتالیا'],
            ['code'=>'IV','iso'=>'CI','tld'=>'.ci','name_en'=>'Cote d\'Ivoire','name_fa'=>'ساحل عاج'],
            ['code'=>'IZ','iso'=>'IQ','tld'=>'.iq','name_en'=>'Iraq','name_fa'=>'عراق'],
            ['code'=>'JA','iso'=>'JP','tld'=>'.jp','name_en'=>'Japan','name_fa'=>'ژاپن'],
            ['code'=>'JE','iso'=>'JE','tld'=>'.je','name_en'=>'Jersey','name_fa'=>'جرسی'],
            ['code'=>'JM','iso'=>'JM','tld'=>'.jm','name_en'=>'Jamaica','name_fa'=>'جامائیکا'],
            ['code'=>'JN','iso'=>'SJ','tld'=>'-','name_en'=>'Jan Mayen','name_fa'=>'Jan Mayen'],
            ['code'=>'JO','iso'=>'JO','tld'=>'.jo','name_en'=>'Jordan','name_fa'=>'اردن'],
            ['code'=>'JQ','iso'=>'UM','tld'=>'-','name_en'=>'Johnston Atoll','name_fa'=>'جانستون اتول'],
            ['code'=>'JU','iso'=>'-','tld'=>'-','name_en'=>'Juan de Nova Island','name_fa'=>'جزیره خوان جزیره نوا'],
            ['code'=>'KE','iso'=>'KE','tld'=>'.ke','name_en'=>'Kenya','name_fa'=>'کنیا'],
            ['code'=>'KG','iso'=>'KG','tld'=>'.kg','name_en'=>'Kyrgyzstan','name_fa'=>'قرقیزستان'],
            ['code'=>'KN','iso'=>'KP','tld'=>'.kp','name_en'=>'Korea, North','name_fa'=>'کره شمالی'],
            ['code'=>'KQ','iso'=>'UM','tld'=>'-','name_en'=>'Kingman Reef','name_fa'=>'کینگمن ریف'],
            ['code'=>'KR','iso'=>'KI','tld'=>'.ki','name_en'=>'Kiribati','name_fa'=>'کیریباتی'],
            ['code'=>'KS','iso'=>'KR','tld'=>'.kr','name_en'=>'Korea, South','name_fa'=>'کره جنوبی'],
            ['code'=>'KT','iso'=>'CX','tld'=>'.cx','name_en'=>'Christmas Island','name_fa'=>'جزیره کریسمس'],
            ['code'=>'KU','iso'=>'KW','tld'=>'.kw','name_en'=>'Kuwait','name_fa'=>'کویت'],
            ['code'=>'KV','iso'=>'KV','tld'=>'-','name_en'=>'Kosovo','name_fa'=>'کوزوو'],
            ['code'=>'KZ','iso'=>'KZ','tld'=>'.kz','name_en'=>'Kazakhstan','name_fa'=>'قزاقستان'],
            ['code'=>'LA','iso'=>'LA','tld'=>'.la','name_en'=>'Laos','name_fa'=>'لائوس'],
            ['code'=>'LE','iso'=>'LB','tld'=>'.lb','name_en'=>'Lebanon','name_fa'=>'لبنان'],
            ['code'=>'LG','iso'=>'LV','tld'=>'.lv','name_en'=>'Latvia','name_fa'=>'لتونی'],
            ['code'=>'LH','iso'=>'LT','tld'=>'.lt','name_en'=>'Lithuania','name_fa'=>'لیتوانی'],
            ['code'=>'LI','iso'=>'LR','tld'=>'.lr','name_en'=>'Liberia','name_fa'=>'لیبریا'],
            ['code'=>'LO','iso'=>'SK','tld'=>'.sk','name_en'=>'Slovakia','name_fa'=>'اسلواکی'],
            ['code'=>'LQ','iso'=>'UM','tld'=>'-','name_en'=>'Palmyra Atoll','name_fa'=>'پالمیرا اتل'],
            ['code'=>'LS','iso'=>'LI','tld'=>'.li','name_en'=>'Liechtenstein','name_fa'=>'لیختن اشتاین'],
            ['code'=>'LT','iso'=>'LS','tld'=>'.ls','name_en'=>'Lesotho','name_fa'=>'لسوتو'],
            ['code'=>'LU','iso'=>'LU','tld'=>'.lu','name_en'=>'Luxembourg','name_fa'=>'لوکزامبورگ'],
            ['code'=>'LY','iso'=>'LY','tld'=>'.ly','name_en'=>'Libyan Arab','name_fa'=>'عرب لیبی'],
            ['code'=>'MA','iso'=>'MG','tld'=>'.mg','name_en'=>'Madagascar','name_fa'=>'ماداگاسکار'],
            ['code'=>'MB','iso'=>'MQ','tld'=>'.mq','name_en'=>'Martinique','name_fa'=>'مارتینیک'],
            ['code'=>'MC','iso'=>'MO','tld'=>'.mo','name_en'=>'Macau','name_fa'=>'ماکائو'],
            ['code'=>'MD','iso'=>'MD','tld'=>'.md','name_en'=>'Moldova, Republic of','name_fa'=>'مولداوی، جمهوری'],
            ['code'=>'MF','iso'=>'YT','tld'=>'.yt','name_en'=>'Mayotte','name_fa'=>'مایوت'],
            ['code'=>'MG','iso'=>'MN','tld'=>'.mn','name_en'=>'Mongolia','name_fa'=>'مغولستان'],
            ['code'=>'MH','iso'=>'MS','tld'=>'.ms','name_en'=>'Montserrat','name_fa'=>'مونتسرات'],
            ['code'=>'MI','iso'=>'MW','tld'=>'.mw','name_en'=>'Malawi','name_fa'=>'مالاوی'],
            ['code'=>'MJ','iso'=>'ME','tld'=>'.me','name_en'=>'Montenegro','name_fa'=>'مونته نگرو'],
            ['code'=>'MK','iso'=>'MK','tld'=>'.mk','name_en'=>'The Former Yugoslav Republic of Macedonia','name_fa'=>'جمهوری مقدونیه یوگسلاوی سابق'],
            ['code'=>'ML','iso'=>'ML','tld'=>'.ml','name_en'=>'Mali','name_fa'=>'مالزی'],
            ['code'=>'MN','iso'=>'MC','tld'=>'.mc','name_en'=>'Monaco','name_fa'=>'موناکو'],
            ['code'=>'MO','iso'=>'MA','tld'=>'.ma','name_en'=>'Morocco','name_fa'=>'مراکش'],
            ['code'=>'MP','iso'=>'MU','tld'=>'.mu','name_en'=>'Mauritius','name_fa'=>'موریس'],
            ['code'=>'MQ','iso'=>'UM','tld'=>'-','name_en'=>'Midway Islands','name_fa'=>'جزایر میدوی'],
            ['code'=>'MR','iso'=>'MR','tld'=>'.mr','name_en'=>'Mauritania','name_fa'=>'موریتانی'],
            ['code'=>'MT','iso'=>'MT','tld'=>'.mt','name_en'=>'Malta','name_fa'=>'مالت'],
            ['code'=>'MU','iso'=>'OM','tld'=>'.om','name_en'=>'Oman','name_fa'=>'عمان'],
            ['code'=>'MV','iso'=>'MV','tld'=>'.mv','name_en'=>'Maldives','name_fa'=>'مالدیو'],
            ['code'=>'MX','iso'=>'MX','tld'=>'.mx','name_en'=>'Mexico','name_fa'=>'مکزیک'],
            ['code'=>'MY','iso'=>'MY','tld'=>'.my','name_en'=>'Malaysia','name_fa'=>'مالزی'],
            ['code'=>'MZ','iso'=>'MZ','tld'=>'.mz','name_en'=>'Mozambique','name_fa'=>'موزامبیک'],
            ['code'=>'NC','iso'=>'NC','tld'=>'.nc','name_en'=>'New Caledonia','name_fa'=>'کالدونیای جدید'],
            ['code'=>'NE','iso'=>'NU','tld'=>'.nu','name_en'=>'Niue','name_fa'=>'نیو'],
            ['code'=>'NF','iso'=>'NF','tld'=>'.nf','name_en'=>'Norfolk Island','name_fa'=>'جزیره نورفولک'],
            ['code'=>'NG','iso'=>'NE','tld'=>'.ne','name_en'=>'Niger','name_fa'=>'نیجر'],
            ['code'=>'NH','iso'=>'VU','tld'=>'.vu','name_en'=>'Vanuatu','name_fa'=>'وانواتو'],
            ['code'=>'NI','iso'=>'NG','tld'=>'.ng','name_en'=>'Nigeria','name_fa'=>'نیجریه'],
            ['code'=>'NL','iso'=>'NL','tld'=>'.nl','name_en'=>'Netherlands','name_fa'=>'هلند'],
            ['code'=>'NM','iso'=>'','tld'=>'','name_en'=>'No Man\'s Land','name_fa'=>'هیچ مردی زمین نیست'],
            ['code'=>'NO','iso'=>'NO','tld'=>'.no','name_en'=>'Norway','name_fa'=>'نروژ'],
            ['code'=>'NP','iso'=>'NP','tld'=>'.np','name_en'=>'Nepal','name_fa'=>'نپال'],
            ['code'=>'NR','iso'=>'NR','tld'=>'.nr','name_en'=>'Nauru','name_fa'=>'نائورو'],
            ['code'=>'NS','iso'=>'SR','tld'=>'.sr','name_en'=>'Suriname','name_fa'=>'سورینام'],
            ['code'=>'NT','iso'=>'AN','tld'=>'.an','name_en'=>'Netherlands Antilles','name_fa'=>'آنتیل هلند'],
            ['code'=>'NU','iso'=>'NI','tld'=>'.ni','name_en'=>'Nicaragua','name_fa'=>'نیکاراگوئه'],
            ['code'=>'NZ','iso'=>'NZ','tld'=>'.nz','name_en'=>'New Zealand','name_fa'=>'نیوزلند'],
            ['code'=>'PA','iso'=>'PY','tld'=>'.py','name_en'=>'Paraguay','name_fa'=>'پاراگوئه'],
            ['code'=>'PC','iso'=>'PN','tld'=>'.pn','name_en'=>'Pitcairn Islands','name_fa'=>'جزایر پیتکرن'],
            ['code'=>'PE','iso'=>'PE','tld'=>'.pe','name_en'=>'Peru','name_fa'=>'پرو'],
            ['code'=>'PF','iso'=>'-','tld'=>'-','name_en'=>'Paracel Islands','name_fa'=>'جزایر پاراسل'],
            ['code'=>'PG','iso'=>'-','tld'=>'-','name_en'=>'Spratly Islands','name_fa'=>'جزایر اسپارتلی'],
            ['code'=>'PK','iso'=>'PK','tld'=>'.pk','name_en'=>'Pakistan','name_fa'=>'پاکستان'],
            ['code'=>'PL','iso'=>'PL','tld'=>'.pl','name_en'=>'Poland','name_fa'=>'لهستان'],
            ['code'=>'PM','iso'=>'PA','tld'=>'.pa','name_en'=>'Panama','name_fa'=>'پاناما'],
            ['code'=>'PO','iso'=>'PT','tld'=>'.pt','name_en'=>'Portugal','name_fa'=>'کشور پرتغال'],
            ['code'=>'PP','iso'=>'PG','tld'=>'.pg','name_en'=>'Papua New Guinea','name_fa'=>'پاپوآ گینه نو'],
            ['code'=>'PS','iso'=>'PW','tld'=>'.pw','name_en'=>'Palau','name_fa'=>'پالائو'],
            ['code'=>'PU','iso'=>'GW','tld'=>'.gw','name_en'=>'Guinea-Bissau','name_fa'=>'گینه بیسائو'],
            ['code'=>'QA','iso'=>'QA','tld'=>'.qa','name_en'=>'Qatar','name_fa'=>'قطر'],
            ['code'=>'RE','iso'=>'RE','tld'=>'.re','name_en'=>'Reunion','name_fa'=>'تجدید دیدار'],
            ['code'=>'RI','iso'=>'RS','tld'=>'.rs','name_en'=>'Serbia','name_fa'=>'صربستان'],
            ['code'=>'RM','iso'=>'MH','tld'=>'.mh','name_en'=>'Marshall Islands','name_fa'=>'جزایر مارشال'],
            ['code'=>'RN','iso'=>'MF','tld'=>'-','name_en'=>'Saint Martin','name_fa'=>'سنت مارتین'],
            ['code'=>'RO','iso'=>'RO','tld'=>'.ro','name_en'=>'Romania','name_fa'=>'رومانی'],
            ['code'=>'RP','iso'=>'PH','tld'=>'.ph','name_en'=>'Philippines','name_fa'=>'فیلیپین'],
            ['code'=>'RQ','iso'=>'PR','tld'=>'.pr','name_en'=>'Puerto Rico','name_fa'=>'پورتوریکو'],
            ['code'=>'RS','iso'=>'RU','tld'=>'.ru','name_en'=>'Russia','name_fa'=>'روسیه'],
            ['code'=>'RW','iso'=>'RW','tld'=>'.rw','name_en'=>'Rwanda','name_fa'=>'رواندا'],
            ['code'=>'SA','iso'=>'SA','tld'=>'.sa','name_en'=>'Saudi Arabia','name_fa'=>'عربستان سعودی'],
            ['code'=>'SB','iso'=>'PM','tld'=>'.pm','name_en'=>'Saint Pierre and Miquelon','name_fa'=>'سنت پیر و میکلون'],
            ['code'=>'SC','iso'=>'KN','tld'=>'.kn','name_en'=>'Saint Kitts and Nevis','name_fa'=>'سنت کیتس و نویس'],
            ['code'=>'SE','iso'=>'SC','tld'=>'.sc','name_en'=>'Seychelles','name_fa'=>'سیشل'],
            ['code'=>'SF','iso'=>'ZA','tld'=>'.za','name_en'=>'South Africa','name_fa'=>'آفریقای جنوبی'],
            ['code'=>'SG','iso'=>'SN','tld'=>'.sn','name_en'=>'Senegal','name_fa'=>'سنگال'],
            ['code'=>'SH','iso'=>'SH','tld'=>'.sh','name_en'=>'Saint Helena','name_fa'=>'سنت هلن'],
            ['code'=>'SI','iso'=>'SI','tld'=>'.si','name_en'=>'Slovenia','name_fa'=>'اسلوونی'],
            ['code'=>'SL','iso'=>'SL','tld'=>'.sl','name_en'=>'Sierra Leone','name_fa'=>'سیرا لئون'],
            ['code'=>'SM','iso'=>'SM','tld'=>'.sm','name_en'=>'San Marino','name_fa'=>'سان مارینو'],
            ['code'=>'SN','iso'=>'SG','tld'=>'.sg','name_en'=>'Singapore','name_fa'=>'سنگاپور'],
            ['code'=>'SO','iso'=>'SO','tld'=>'.so','name_en'=>'Somalia','name_fa'=>'سومالی'],
            ['code'=>'SP','iso'=>'ES','tld'=>'.es','name_en'=>'Spain','name_fa'=>'اسپانیا'],
            ['code'=>'ST','iso'=>'LC','tld'=>'.lc','name_en'=>'Saint Lucia','name_fa'=>'سنت لوسیا'],
            ['code'=>'SU','iso'=>'SD','tld'=>'.sd','name_en'=>'Sudan','name_fa'=>'سودان'],
            ['code'=>'SV','iso'=>'SJ','tld'=>'.sj','name_en'=>'Svalbard','name_fa'=>'اسباب بازی'],
            ['code'=>'SW','iso'=>'SE','tld'=>'.se','name_en'=>'Sweden','name_fa'=>'سوئد'],
            ['code'=>'SX','iso'=>'GS','tld'=>'.gs','name_en'=>'South Georgia and the Islands','name_fa'=>'جنوب گرجستان و جزایر'],
            ['code'=>'SY','iso'=>'SY','tld'=>'.sy','name_en'=>'Syrian Arab Republic','name_fa'=>'جمهوری عربی سوریه'],
            ['code'=>'SZ','iso'=>'CH','tld'=>'.ch','name_en'=>'Switzerland','name_fa'=>'سوئیس'],
            ['code'=>'TD','iso'=>'TT','tld'=>'.tt','name_en'=>'Trinidad and Tobago','name_fa'=>'ترینیداد و توباگو'],
            ['code'=>'TE','iso'=>'-','tld'=>'-','name_en'=>'Tromelin Island','name_fa'=>'جزیره ترولین'],
            ['code'=>'TH','iso'=>'TH','tld'=>'.th','name_en'=>'Thailand','name_fa'=>'تایلند'],
            ['code'=>'TI','iso'=>'TJ','tld'=>'.tj','name_en'=>'Tajikistan','name_fa'=>'تاجیکستان'],
            ['code'=>'TK','iso'=>'TC','tld'=>'.tc','name_en'=>'Turks and Caicos Islands','name_fa'=>'جزایر ترکس و کایکوس'],
            ['code'=>'TL','iso'=>'TK','tld'=>'.tk','name_en'=>'Tokelau','name_fa'=>'توکلو'],
            ['code'=>'TN','iso'=>'TO','tld'=>'.to','name_en'=>'Tonga','name_fa'=>'تونگا'],
            ['code'=>'TO','iso'=>'TG','tld'=>'.tg','name_en'=>'Togo','name_fa'=>'رفتن'],
            ['code'=>'TP','iso'=>'ST','tld'=>'.st','name_en'=>'Sao Tome and Principe','name_fa'=>'سائوتومه و پرنسیپه'],
            ['code'=>'TS','iso'=>'TN','tld'=>'.tn','name_en'=>'Tunisia','name_fa'=>'تونس'],
            ['code'=>'TT','iso'=>'TL','tld'=>'.tl','name_en'=>'East Timor','name_fa'=>'تیمور شرقی'],
            ['code'=>'TU','iso'=>'TR','tld'=>'.tr','name_en'=>'Turkey','name_fa'=>'ترکیه'],
            ['code'=>'TV','iso'=>'TV','tld'=>'.tv','name_en'=>'Tuvalu','name_fa'=>'توووالو'],
            ['code'=>'TW','iso'=>'TW','tld'=>'.tw','name_en'=>'Taiwan','name_fa'=>'تایوان'],
            ['code'=>'TX','iso'=>'TM','tld'=>'.tm','name_en'=>'Turkmenistan','name_fa'=>'ترکمنستان'],
            ['code'=>'TZ','iso'=>'TZ','tld'=>'.tz','name_en'=>'Tanzania, United Republic of','name_fa'=>'تانزانیا، جمهوری متحده'],
            ['code'=>'UG','iso'=>'UG','tld'=>'.ug','name_en'=>'Uganda','name_fa'=>'اوگاندا'],
            ['code'=>'UK','iso'=>'GB','tld'=>'.uk','name_en'=>'United Kingdom','name_fa'=>'انگلستان'],
            ['code'=>'UP','iso'=>'UA','tld'=>'.ua','name_en'=>'Ukraine','name_fa'=>'اوکراین'],
            ['code'=>'US','iso'=>'US','tld'=>'.us','name_en'=>'United States','name_fa'=>'ایالات متحده'],
            ['code'=>'UV','iso'=>'BF','tld'=>'.bf','name_en'=>'Burkina Faso','name_fa'=>'بورکینافاسو'],
            ['code'=>'UY','iso'=>'UY','tld'=>'.uy','name_en'=>'Uruguay','name_fa'=>'اروگوئه'],
            ['code'=>'UZ','iso'=>'UZ','tld'=>'.uz','name_en'=>'Uzbekistan','name_fa'=>'ازبکستان'],
            ['code'=>'VC','iso'=>'VC','tld'=>'.vc','name_en'=>'Saint Vincent and the Grenadines','name_fa'=>'سنت وینسنت و گرنادین'],
            ['code'=>'VE','iso'=>'VE','tld'=>'.ve','name_en'=>'Venezuela','name_fa'=>'ونزوئلا'],
            ['code'=>'VI','iso'=>'VG','tld'=>'.vg','name_en'=>'British Virgin Islands','name_fa'=>'جزایر ویرجین بریتانیا'],
            ['code'=>'VM','iso'=>'VN','tld'=>'.vn','name_en'=>'Vietnam','name_fa'=>'ویتنام'],
            ['code'=>'VQ','iso'=>'VI','tld'=>'.vi','name_en'=>'Virgin Islands (US)','name_fa'=>'جزایر ویرجین (ایالات متحده)'],
            ['code'=>'VT','iso'=>'VA','tld'=>'.va','name_en'=>'Holy See (Vatican City)','name_fa'=>'مقدس (واتیکان)'],
            ['code'=>'WA','iso'=>'NA','tld'=>'.na','name_en'=>'Namibia','name_fa'=>'نامیبیا'],
            ['code'=>'WE','iso'=>'-','tld'=>'-','name_en'=>'West Bank','name_fa'=>'بانک غرب'],
            ['code'=>'WF','iso'=>'WF','tld'=>'.wf','name_en'=>'Wallis and Futuna','name_fa'=>'والیس و فوتونا'],
            ['code'=>'WI','iso'=>'EH','tld'=>'.eh','name_en'=>'Western Sahara','name_fa'=>'صحرای غربی'],
            ['code'=>'WQ','iso'=>'UM','tld'=>'-','name_en'=>'Wake Island','name_fa'=>'جزیره ویک'],
            ['code'=>'WS','iso'=>'WS','tld'=>'.ws','name_en'=>'Samoa','name_fa'=>'ساموآ'],
            ['code'=>'WZ','iso'=>'SZ','tld'=>'.sz','name_en'=>'Swaziland','name_fa'=>'سوازیلند'],
            ['code'=>'YI','iso'=>'CS','tld'=>'.yu','name_en'=>'Serbia and Montenegro','name_fa'=>'صربستان و مونته نگرو'],
            ['code'=>'YM','iso'=>'YE','tld'=>'.ye','name_en'=>'Yemen','name_fa'=>'یمن'],
            ['code'=>'ZA','iso'=>'ZM','tld'=>'.zm','name_en'=>'Zambia','name_fa'=>'زامبیا'],
            ['code'=>'ZI','iso'=>'ZW','tld'=>'.zw','name_en'=>'Zimbabwe','name_fa'=>'زیمبابوه']
        ];


        $countries = array_map(fn($row) => array_merge($row, [
            'created_at' => now(),
            'updated_at' => now(),
        ]), $countries);
        Country::query()->insertOrIgnore($countries);
    }
}
