SET NAMES utf8mb4;

INSERT INTO `countries` VALUES (1, 'AA', 'AW', '.aw', 'Aruba', 'آروبا');
INSERT INTO `countries` VALUES (2, 'AC', 'AG', '.ag', 'Antigua and Barbuda', 'آنتیگوا و باربودا');
INSERT INTO `countries` VALUES (3, 'AE', 'AE', '.ae', 'United Arab Emirates', 'امارات متحده عربی');
INSERT INTO `countries` VALUES (4, 'AF', 'AF', '.af', 'Afghanistan', 'افغانستان');
INSERT INTO `countries` VALUES (5, 'AG', 'DZ', '.dz', 'Algeria', 'الجزایر');
INSERT INTO `countries` VALUES (6, 'AJ', 'AZ', '.az', 'Azerbaijan', 'آذربایجان');
INSERT INTO `countries` VALUES (7, 'AL', 'AL', '.al', 'Albania', 'آلبانی');
INSERT INTO `countries` VALUES (8, 'AM', 'AM', '.am', 'Armenia', 'ارمنستان');
INSERT INTO `countries` VALUES (9, 'AN', 'AD', '.ad', 'Andorra', 'آندورا');
INSERT INTO `countries` VALUES (10, 'AO', 'AO', '.ao', 'Angola', 'آنگولا');
INSERT INTO `countries` VALUES (11, 'AQ', 'AS', '.as', 'American Samoa', 'ساموای آمریکایی');
INSERT INTO `countries` VALUES (12, 'AR', 'AR', '.ar', 'Argentina', 'آرژانتین');
INSERT INTO `countries` VALUES (13, 'AS', 'AU', '.au', 'Australia', 'استرالیا');
INSERT INTO `countries` VALUES (14, 'AT', '-', '-', 'Ashmore and Cartier Islands', 'اشکمور و جزایر کارتیه');
INSERT INTO `countries` VALUES (15, 'AU', 'AT', '.at', 'Austria', 'اتریش');
INSERT INTO `countries` VALUES (16, 'AV', 'AI', '.ai', 'Anguilla', 'آنگویلا');
INSERT INTO `countries` VALUES (17, 'AX', 'AX', '.ax', 'Åland Islands', 'جزایر الند');
INSERT INTO `countries` VALUES (18, 'AY', 'AQ', '.aq', 'Antarctica', 'قطب جنوب');
INSERT INTO `countries` VALUES (19, 'BA', 'BH', '.bh', 'Bahrain', 'بحرین');
INSERT INTO `countries` VALUES (20, 'BB', 'BB', '.bb', 'Barbados', 'باربادوس');
INSERT INTO `countries` VALUES (21, 'BC', 'BW', '.bw', 'Botswana', 'بوتسوانا');
INSERT INTO `countries` VALUES (22, 'BD', 'BM', '.bm', 'Bermuda', 'برمودا');
INSERT INTO `countries` VALUES (23, 'BE', 'BE', '.be', 'Belgium', 'بلژیک');
INSERT INTO `countries` VALUES (24, 'BF', 'BS', '.bs', 'Bahamas, The', 'باهاما، The');
INSERT INTO `countries` VALUES (25, 'BG', 'BD', '.bd', 'Bangladesh', 'بنگلادش');
INSERT INTO `countries` VALUES (26, 'BH', 'BZ', '.bz', 'Belize', 'بلیز');
INSERT INTO `countries` VALUES (27, 'BK', 'BA', '.ba', 'Bosnia and Herzegovina', 'بوسنی و هرزگوین');
INSERT INTO `countries` VALUES (28, 'BL', 'BO', '.bo', 'Bolivia', 'بولیوی');
INSERT INTO `countries` VALUES (29, 'BM', 'MM', '.mm', 'Myanmar', 'میانمار');
INSERT INTO `countries` VALUES (30, 'BN', 'BJ', '.bj', 'Benin', 'بنین');
INSERT INTO `countries` VALUES (31, 'BO', 'BY', '.by', 'Belarus', 'بلاروس');
INSERT INTO `countries` VALUES (32, 'BP', 'SB', '.sb', 'Solomon Islands', 'جزایر سلیمان');
INSERT INTO `countries` VALUES (33, 'BQ', '-', '-', 'Navassa Island', 'جزیره ناواسا');
INSERT INTO `countries` VALUES (34, 'BR', 'BR', '.br', 'Brazil', 'برزیل');
INSERT INTO `countries` VALUES (35, 'BS', '-', '-', 'Bassas da India', 'باساس دا هند');
INSERT INTO `countries` VALUES (36, 'BT', 'BT', '.bt', 'Bhutan', 'بوتان');
INSERT INTO `countries` VALUES (37, 'BU', 'BG', '.bg', 'Bulgaria', 'بلغارستان');
INSERT INTO `countries` VALUES (38, 'BV', 'BV', '.bv', 'Bouvet Island', 'جزیره Bouvet');
INSERT INTO `countries` VALUES (39, 'BX', 'BN', '.bn', 'Brunei', 'برونئی');
INSERT INTO `countries` VALUES (40, 'BY', 'BI', '.bi', 'Burundi', 'بوروندی');
INSERT INTO `countries` VALUES (41, 'CA', 'CA', '.ca', 'Canada', 'کانادا');
INSERT INTO `countries` VALUES (42, 'CB', 'KH', '.kh', 'Cambodia', 'کامبوج');
INSERT INTO `countries` VALUES (43, 'CD', 'TD', '.td', 'Chad', 'چاد');
INSERT INTO `countries` VALUES (44, 'CE', 'LK', '.lk', 'Sri Lanka', 'سری لانکا');
INSERT INTO `countries` VALUES (45, 'CF', 'CG', '.cg', 'Congo, Republic of the', 'کنگو، جمهوری');
INSERT INTO `countries` VALUES (46, 'CG', 'CD', '.cd', 'Congo, Democratic Republic of the', 'کنگو، جمهوری دموکراتیک');
INSERT INTO `countries` VALUES (47, 'CH', 'CN', '.cn', 'China', 'چين');
INSERT INTO `countries` VALUES (48, 'CI', 'CL', '.cl', 'Chile', 'شیلی');
INSERT INTO `countries` VALUES (49, 'CJ', 'KY', '.ky', 'Cayman Islands', 'جزایر کیمن');
INSERT INTO `countries` VALUES (50, 'CK', 'CC', '.cc', 'Cocos (Keeling) Islands', 'جزایر کوکوس (کایلینگ)');
INSERT INTO `countries` VALUES (51, 'CM', 'CM', '.cm', 'Cameroon', 'کامرون');
INSERT INTO `countries` VALUES (52, 'CN', 'KM', '.km', 'Comoros', 'کومور');
INSERT INTO `countries` VALUES (53, 'CO', 'CO', '.co', 'Colombia', 'کلمبیا');
INSERT INTO `countries` VALUES (54, 'CQ', 'MP', '.mp', 'Northern Mariana Islands', 'جزایر ماریانای شمالی');
INSERT INTO `countries` VALUES (55, 'CR', '-', '-', 'Coral Sea Islands', 'جزایر دریای مرجانی');
INSERT INTO `countries` VALUES (56, 'CS', 'CR', '.cr', 'Costa Rica', 'کاستاریکا');
INSERT INTO `countries` VALUES (57, 'CT', 'CF', '.cf', 'Central African Republic', 'جمهوری آفریقای مرکزی');
INSERT INTO `countries` VALUES (58, 'CU', 'CU', '.cu', 'Cuba', 'کوبا');
INSERT INTO `countries` VALUES (59, 'CV', 'CV', '.cv', 'Cape Verde', 'کیپ ورد');
INSERT INTO `countries` VALUES (60, 'CW', 'CK', '.ck', 'Cook Islands', 'جزایر کوک');
INSERT INTO `countries` VALUES (61, 'CY', 'CY', '.cy', 'Cyprus', 'قبرس');
INSERT INTO `countries` VALUES (62, 'DA', 'DK', '.dk', 'Denmark', 'دانمارک');
INSERT INTO `countries` VALUES (63, 'DJ', 'DJ', '.dj', 'Djibouti', 'جیبوتی');
INSERT INTO `countries` VALUES (64, 'DO', 'DM', '.dm', 'Dominica', 'دومینیکا');
INSERT INTO `countries` VALUES (65, 'DQ', 'UM', '-', 'Jarvis Island', 'جزیره جارویس');
INSERT INTO `countries` VALUES (66, 'DR', 'DO', '.do', 'Dominican Republic', 'جمهوری دومینیکن');
INSERT INTO `countries` VALUES (67, 'DX', '-', '-', 'Dhekelia Sovereign Base Area', 'منطقه ممنوعه Dhekelia');
INSERT INTO `countries` VALUES (68, 'EC', 'EC', '.ec', 'Ecuador', 'اکوادور');
INSERT INTO `countries` VALUES (69, 'EG', 'EG', '.eg', 'Egypt', 'مصر');
INSERT INTO `countries` VALUES (70, 'EI', 'IE', '.ie', 'Ireland', 'ایرلند');
INSERT INTO `countries` VALUES (71, 'EK', 'GQ', '.gq', 'Equatorial Guinea', 'گینه استوایی');
INSERT INTO `countries` VALUES (72, 'EN', 'EE', '.ee', 'Estonia', 'استونی');
INSERT INTO `countries` VALUES (73, 'ER', 'ER', '.er', 'Eritrea', 'اریتره');
INSERT INTO `countries` VALUES (74, 'ES', 'SV', '.sv', 'El Salvador', 'السالوادور');
INSERT INTO `countries` VALUES (75, 'ET', 'ET', '.et', 'Ethiopia', 'اتیوپی');
INSERT INTO `countries` VALUES (76, 'EU', '-', '-', 'Europa Island', 'جزیره اروپا');
INSERT INTO `countries` VALUES (77, 'EZ', 'CZ', '.cz', 'Czech Republic', 'جمهوری چک');
INSERT INTO `countries` VALUES (78, 'FG', 'GF', '.gf', 'French Guiana', 'گویان فرانسه');
INSERT INTO `countries` VALUES (79, 'FI', 'FI', '.fi', 'Finland', 'فنلاند');
INSERT INTO `countries` VALUES (80, 'FJ', 'FJ', '.fj', 'Fiji', 'فیجی');
INSERT INTO `countries` VALUES (81, 'FK', 'FK', '.fk', 'Falkland Islands (Islas Malvinas)', 'جزایر فالکلند (جزایر مالویناس)');
INSERT INTO `countries` VALUES (82, 'FM', 'FM', '.fm', 'Micronesia, Federated States of', 'میکرونزی، ایالات فدرال');
INSERT INTO `countries` VALUES (83, 'FO', 'FO', '.fo', 'Faroe Islands', 'جزایر فارو');
INSERT INTO `countries` VALUES (84, 'FP', 'PF', '.pf', 'French Polynesia', 'پلینزی فرانسه');
INSERT INTO `countries` VALUES (85, 'FQ', 'UM', '-', 'Baker Island', 'جزیره بیکر');
INSERT INTO `countries` VALUES (86, 'FR', 'FR', '.fr', 'France', 'فرانسه');
INSERT INTO `countries` VALUES (87, 'FS', 'TF', '.tf', 'French Southern and Antarctic Lands', 'زمینهای جنوب و جنوب قطب جنوب فرانسه');
INSERT INTO `countries` VALUES (88, 'GA', 'GM', '.gm', 'Gambia, The', 'گامبیا، The');
INSERT INTO `countries` VALUES (89, 'GB', 'GA', '.ga', 'Gabon', 'گابن');
INSERT INTO `countries` VALUES (90, 'GG', 'GE', '.ge', 'Georgia', 'جورجیا');
INSERT INTO `countries` VALUES (91, 'GH', 'GH', '.gh', 'Ghana', 'غنا');
INSERT INTO `countries` VALUES (92, 'GI', 'GI', '.gi', 'Gibraltar', 'جبل الطارق');
INSERT INTO `countries` VALUES (93, 'GJ', 'GD', '.gd', 'Grenada', 'گرانادا');
INSERT INTO `countries` VALUES (94, 'GK', '-', '.gg', 'Guernsey', 'گورنسی');
INSERT INTO `countries` VALUES (95, 'GL', 'GL', '.gl', 'Greenland', 'گرینلند');
INSERT INTO `countries` VALUES (96, 'GM', 'DE', '.de', 'Germany', 'آلمان');
INSERT INTO `countries` VALUES (97, 'GO', '-', '-', 'Glorioso Islands', 'جزایر گلوریوزو');
INSERT INTO `countries` VALUES (98, 'GP', 'GP', '.gp', 'Guadeloupe', 'گوادلوپ');
INSERT INTO `countries` VALUES (99, 'GQ', 'GU', '.gu', 'Guam', 'گوام');
INSERT INTO `countries` VALUES (100, 'GR', 'GR', '.gr', 'Greece', 'یونان');
INSERT INTO `countries` VALUES (101, 'GT', 'GT', '.gt', 'Guatemala', 'گواتمالا');
INSERT INTO `countries` VALUES (102, 'GV', 'GN', '.gn', 'Guinea', 'گینه');
INSERT INTO `countries` VALUES (103, 'GY', 'GY', '.gy', 'Guyana', 'گایانا');
INSERT INTO `countries` VALUES (104, 'GZ', '-', '-', 'Gaza Strip', 'نوار غزه');
INSERT INTO `countries` VALUES (105, 'HA', 'HT', '.ht', 'Haiti', 'هائیتی');
INSERT INTO `countries` VALUES (106, 'HK', 'HK', '.hk', 'Hong Kong', 'هنگ کنگ');
INSERT INTO `countries` VALUES (107, 'HM', 'HM', '.hm', 'Heard Island and McDonald Islands', 'جزایر هرد و جزایر مک دونالد');
INSERT INTO `countries` VALUES (108, 'HO', 'HN', '.hn', 'Honduras', 'هندوراس');
INSERT INTO `countries` VALUES (109, 'HQ', 'UM', '-', 'Howland Island', 'جزیره Howland');
INSERT INTO `countries` VALUES (110, 'HR', 'HR', '.hr', 'Croatia', 'کرواسی');
INSERT INTO `countries` VALUES (111, 'HU', 'HU', '.hu', 'Hungary', 'مجارستان');
INSERT INTO `countries` VALUES (112, 'IC', 'IS', '.is', 'Iceland', 'ایسلند');
INSERT INTO `countries` VALUES (113, 'ID', 'ID', '.id', 'Indonesia', 'اندونزی');
INSERT INTO `countries` VALUES (114, 'IM', 'IM', '.im', 'Isle of Man', 'جزیره من');
INSERT INTO `countries` VALUES (115, 'IN', 'IN', '.in', 'India', 'هندوستان');
INSERT INTO `countries` VALUES (116, 'IO', 'IO', '.io', 'British Indian Ocean Territory', 'قلمرو اقیانوس هند بریتانیا');
INSERT INTO `countries` VALUES (117, 'IP', '-', '-', 'Clipperton Island', 'جزیره Clipperton');
INSERT INTO `countries` VALUES (118, 'IR', 'IR', '.ir', 'Iran', 'ایران');
INSERT INTO `countries` VALUES (119, 'IS', 'IL', '.il', 'Israel', 'اسرائيل');
INSERT INTO `countries` VALUES (120, 'IT', 'IT', '.it', 'Italy', 'ایتالیا');
INSERT INTO `countries` VALUES (121, 'IV', 'CI', '.ci', 'Cote d\'Ivoire', 'ساحل عاج');
INSERT INTO `countries` VALUES (122, 'IZ', 'IQ', '.iq', 'Iraq', 'عراق');
INSERT INTO `countries` VALUES (123, 'JA', 'JP', '.jp', 'Japan', 'ژاپن');
INSERT INTO `countries` VALUES (124, 'JE', 'JE', '.je', 'Jersey', 'جرسی');
INSERT INTO `countries` VALUES (125, 'JM', 'JM', '.jm', 'Jamaica', 'جامائیکا');
INSERT INTO `countries` VALUES (126, 'JN', 'SJ', '-', 'Jan Mayen', 'Jan Mayen');
INSERT INTO `countries` VALUES (127, 'JO', 'JO', '.jo', 'Jordan', 'اردن');
INSERT INTO `countries` VALUES (128, 'JQ', 'UM', '-', 'Johnston Atoll', 'جانستون اتول');
INSERT INTO `countries` VALUES (129, 'JU', '-', '-', 'Juan de Nova Island', 'جزیره خوان جزیره نوا');
INSERT INTO `countries` VALUES (130, 'KE', 'KE', '.ke', 'Kenya', 'کنیا');
INSERT INTO `countries` VALUES (131, 'KG', 'KG', '.kg', 'Kyrgyzstan', 'قرقیزستان');
INSERT INTO `countries` VALUES (132, 'KN', 'KP', '.kp', 'Korea, North', 'کره شمالی');
INSERT INTO `countries` VALUES (133, 'KQ', 'UM', '-', 'Kingman Reef', 'کینگمن ریف');
INSERT INTO `countries` VALUES (134, 'KR', 'KI', '.ki', 'Kiribati', 'کیریباتی');
INSERT INTO `countries` VALUES (135, 'KS', 'KR', '.kr', 'Korea, South', 'کره جنوبی');
INSERT INTO `countries` VALUES (136, 'KT', 'CX', '.cx', 'Christmas Island', 'جزیره کریسمس');
INSERT INTO `countries` VALUES (137, 'KU', 'KW', '.kw', 'Kuwait', 'کویت');
INSERT INTO `countries` VALUES (138, 'KV', 'KV', '-', 'Kosovo', 'کوزوو');
INSERT INTO `countries` VALUES (139, 'KZ', 'KZ', '.kz', 'Kazakhstan', 'قزاقستان');
INSERT INTO `countries` VALUES (140, 'LA', 'LA', '.la', 'Laos', 'لائوس');
INSERT INTO `countries` VALUES (141, 'LE', 'LB', '.lb', 'Lebanon', 'لبنان');
INSERT INTO `countries` VALUES (142, 'LG', 'LV', '.lv', 'Latvia', 'لتونی');
INSERT INTO `countries` VALUES (143, 'LH', 'LT', '.lt', 'Lithuania', 'لیتوانی');
INSERT INTO `countries` VALUES (144, 'LI', 'LR', '.lr', 'Liberia', 'لیبریا');
INSERT INTO `countries` VALUES (145, 'LO', 'SK', '.sk', 'Slovakia', 'اسلواکی');
INSERT INTO `countries` VALUES (146, 'LQ', 'UM', '-', 'Palmyra Atoll', 'پالمیرا اتل');
INSERT INTO `countries` VALUES (147, 'LS', 'LI', '.li', 'Liechtenstein', 'لیختن اشتاین');
INSERT INTO `countries` VALUES (148, 'LT', 'LS', '.ls', 'Lesotho', 'لسوتو');
INSERT INTO `countries` VALUES (149, 'LU', 'LU', '.lu', 'Luxembourg', 'لوکزامبورگ');
INSERT INTO `countries` VALUES (150, 'LY', 'LY', '.ly', 'Libyan Arab', 'عرب لیبی');
INSERT INTO `countries` VALUES (151, 'MA', 'MG', '.mg', 'Madagascar', 'ماداگاسکار');
INSERT INTO `countries` VALUES (152, 'MB', 'MQ', '.mq', 'Martinique', 'مارتینیک');
INSERT INTO `countries` VALUES (153, 'MC', 'MO', '.mo', 'Macau', 'ماکائو');
INSERT INTO `countries` VALUES (154, 'MD', 'MD', '.md', 'Moldova, Republic of', 'مولداوی، جمهوری');
INSERT INTO `countries` VALUES (155, 'MF', 'YT', '.yt', 'Mayotte', 'مایوت');
INSERT INTO `countries` VALUES (156, 'MG', 'MN', '.mn', 'Mongolia', 'مغولستان');
INSERT INTO `countries` VALUES (157, 'MH', 'MS', '.ms', 'Montserrat', 'مونتسرات');
INSERT INTO `countries` VALUES (158, 'MI', 'MW', '.mw', 'Malawi', 'مالاوی');
INSERT INTO `countries` VALUES (159, 'MJ', 'ME', '.me', 'Montenegro', 'مونته نگرو');
INSERT INTO `countries` VALUES (160, 'MK', 'MK', '.mk', 'The Former Yugoslav Republic of Macedonia', 'جمهوری مقدونیه یوگسلاوی سابق');
INSERT INTO `countries` VALUES (161, 'ML', 'ML', '.ml', 'Mali', 'مالزی');
INSERT INTO `countries` VALUES (162, 'MN', 'MC', '.mc', 'Monaco', 'موناکو');
INSERT INTO `countries` VALUES (163, 'MO', 'MA', '.ma', 'Morocco', 'مراکش');
INSERT INTO `countries` VALUES (164, 'MP', 'MU', '.mu', 'Mauritius', 'موریس');
INSERT INTO `countries` VALUES (165, 'MQ', 'UM', '-', 'Midway Islands', 'جزایر میدوی');
INSERT INTO `countries` VALUES (166, 'MR', 'MR', '.mr', 'Mauritania', 'موریتانی');
INSERT INTO `countries` VALUES (167, 'MT', 'MT', '.mt', 'Malta', 'مالت');
INSERT INTO `countries` VALUES (168, 'MU', 'OM', '.om', 'Oman', 'عمان');
INSERT INTO `countries` VALUES (169, 'MV', 'MV', '.mv', 'Maldives', 'مالدیو');
INSERT INTO `countries` VALUES (170, 'MX', 'MX', '.mx', 'Mexico', 'مکزیک');
INSERT INTO `countries` VALUES (171, 'MY', 'MY', '.my', 'Malaysia', 'مالزی');
INSERT INTO `countries` VALUES (172, 'MZ', 'MZ', '.mz', 'Mozambique', 'موزامبیک');
INSERT INTO `countries` VALUES (173, 'NC', 'NC', '.nc', 'New Caledonia', 'کالدونیای جدید');
INSERT INTO `countries` VALUES (174, 'NE', 'NU', '.nu', 'Niue', 'نیو');
INSERT INTO `countries` VALUES (175, 'NF', 'NF', '.nf', 'Norfolk Island', 'جزیره نورفولک');
INSERT INTO `countries` VALUES (176, 'NG', 'NE', '.ne', 'Niger', 'نیجر');
INSERT INTO `countries` VALUES (177, 'NH', 'VU', '.vu', 'Vanuatu', 'وانواتو');
INSERT INTO `countries` VALUES (178, 'NI', 'NG', '.ng', 'Nigeria', 'نیجریه');
INSERT INTO `countries` VALUES (179, 'NL', 'NL', '.nl', 'Netherlands', 'هلند');
INSERT INTO `countries` VALUES (180, 'NM', '', '', 'No Man\'s Land', 'هیچ مردی زمین نیست');
INSERT INTO `countries` VALUES (181, 'NO', 'NO', '.no', 'Norway', 'نروژ');
INSERT INTO `countries` VALUES (182, 'NP', 'NP', '.np', 'Nepal', 'نپال');
INSERT INTO `countries` VALUES (183, 'NR', 'NR', '.nr', 'Nauru', 'نائورو');
INSERT INTO `countries` VALUES (184, 'NS', 'SR', '.sr', 'Suriname', 'سورینام');
INSERT INTO `countries` VALUES (185, 'NT', 'AN', '.an', 'Netherlands Antilles', 'آنتیل هلند');
INSERT INTO `countries` VALUES (186, 'NU', 'NI', '.ni', 'Nicaragua', 'نیکاراگوئه');
INSERT INTO `countries` VALUES (187, 'NZ', 'NZ', '.nz', 'New Zealand', 'نیوزلند');
INSERT INTO `countries` VALUES (188, 'PA', 'PY', '.py', 'Paraguay', 'پاراگوئه');
INSERT INTO `countries` VALUES (189, 'PC', 'PN', '.pn', 'Pitcairn Islands', 'جزایر پیتکرن');
INSERT INTO `countries` VALUES (190, 'PE', 'PE', '.pe', 'Peru', 'پرو');
INSERT INTO `countries` VALUES (191, 'PF', '-', '-', 'Paracel Islands', 'جزایر پاراسل');
INSERT INTO `countries` VALUES (192, 'PG', '-', '-', 'Spratly Islands', 'جزایر اسپارتلی');
INSERT INTO `countries` VALUES (193, 'PK', 'PK', '.pk', 'Pakistan', 'پاکستان');
INSERT INTO `countries` VALUES (194, 'PL', 'PL', '.pl', 'Poland', 'لهستان');
INSERT INTO `countries` VALUES (195, 'PM', 'PA', '.pa', 'Panama', 'پاناما');
INSERT INTO `countries` VALUES (196, 'PO', 'PT', '.pt', 'Portugal', 'کشور پرتغال');
INSERT INTO `countries` VALUES (197, 'PP', 'PG', '.pg', 'Papua New Guinea', 'پاپوآ گینه نو');
INSERT INTO `countries` VALUES (198, 'PS', 'PW', '.pw', 'Palau', 'پالائو');
INSERT INTO `countries` VALUES (199, 'PU', 'GW', '.gw', 'Guinea-Bissau', 'گینه بیسائو');
INSERT INTO `countries` VALUES (200, 'QA', 'QA', '.qa', 'Qatar', 'قطر');
INSERT INTO `countries` VALUES (201, 'RE', 'RE', '.re', 'Reunion', 'تجدید دیدار');
INSERT INTO `countries` VALUES (202, 'RI', 'RS', '.rs', 'Serbia', 'صربستان');
INSERT INTO `countries` VALUES (203, 'RM', 'MH', '.mh', 'Marshall Islands', 'جزایر مارشال');
INSERT INTO `countries` VALUES (204, 'RN', 'MF', '-', 'Saint Martin', 'سنت مارتین');
INSERT INTO `countries` VALUES (205, 'RO', 'RO', '.ro', 'Romania', 'رومانی');
INSERT INTO `countries` VALUES (206, 'RP', 'PH', '.ph', 'Philippines', 'فیلیپین');
INSERT INTO `countries` VALUES (207, 'RQ', 'PR', '.pr', 'Puerto Rico', 'پورتوریکو');
INSERT INTO `countries` VALUES (208, 'RS', 'RU', '.ru', 'Russia', 'روسیه');
INSERT INTO `countries` VALUES (209, 'RW', 'RW', '.rw', 'Rwanda', 'رواندا');
INSERT INTO `countries` VALUES (210, 'SA', 'SA', '.sa', 'Saudi Arabia', 'عربستان سعودی');
INSERT INTO `countries` VALUES (211, 'SB', 'PM', '.pm', 'Saint Pierre and Miquelon', 'سنت پیر و میکلون');
INSERT INTO `countries` VALUES (212, 'SC', 'KN', '.kn', 'Saint Kitts and Nevis', 'سنت کیتس و نویس');
INSERT INTO `countries` VALUES (213, 'SE', 'SC', '.sc', 'Seychelles', 'سیشل');
INSERT INTO `countries` VALUES (214, 'SF', 'ZA', '.za', 'South Africa', 'آفریقای جنوبی');
INSERT INTO `countries` VALUES (215, 'SG', 'SN', '.sn', 'Senegal', 'سنگال');
INSERT INTO `countries` VALUES (216, 'SH', 'SH', '.sh', 'Saint Helena', 'سنت هلن');
INSERT INTO `countries` VALUES (217, 'SI', 'SI', '.si', 'Slovenia', 'اسلوونی');
INSERT INTO `countries` VALUES (218, 'SL', 'SL', '.sl', 'Sierra Leone', 'سیرا لئون');
INSERT INTO `countries` VALUES (219, 'SM', 'SM', '.sm', 'San Marino', 'سان مارینو');
INSERT INTO `countries` VALUES (220, 'SN', 'SG', '.sg', 'Singapore', 'سنگاپور');
INSERT INTO `countries` VALUES (221, 'SO', 'SO', '.so', 'Somalia', 'سومالی');
INSERT INTO `countries` VALUES (222, 'SP', 'ES', '.es', 'Spain', 'اسپانیا');
INSERT INTO `countries` VALUES (223, 'ST', 'LC', '.lc', 'Saint Lucia', 'سنت لوسیا');
INSERT INTO `countries` VALUES (224, 'SU', 'SD', '.sd', 'Sudan', 'سودان');
INSERT INTO `countries` VALUES (225, 'SV', 'SJ', '.sj', 'Svalbard', 'اسباب بازی');
INSERT INTO `countries` VALUES (226, 'SW', 'SE', '.se', 'Sweden', 'سوئد');
INSERT INTO `countries` VALUES (227, 'SX', 'GS', '.gs', 'South Georgia and the Islands', 'جنوب گرجستان و جزایر');
INSERT INTO `countries` VALUES (228, 'SY', 'SY', '.sy', 'Syrian Arab Republic', 'جمهوری عربی سوریه');
INSERT INTO `countries` VALUES (229, 'SZ', 'CH', '.ch', 'Switzerland', 'سوئیس');
INSERT INTO `countries` VALUES (230, 'TD', 'TT', '.tt', 'Trinidad and Tobago', 'ترینیداد و توباگو');
INSERT INTO `countries` VALUES (231, 'TE', '-', '-', 'Tromelin Island', 'جزیره ترولین');
INSERT INTO `countries` VALUES (232, 'TH', 'TH', '.th', 'Thailand', 'تایلند');
INSERT INTO `countries` VALUES (233, 'TI', 'TJ', '.tj', 'Tajikistan', 'تاجیکستان');
INSERT INTO `countries` VALUES (234, 'TK', 'TC', '.tc', 'Turks and Caicos Islands', 'جزایر ترکس و کایکوس');
INSERT INTO `countries` VALUES (235, 'TL', 'TK', '.tk', 'Tokelau', 'توکلو');
INSERT INTO `countries` VALUES (236, 'TN', 'TO', '.to', 'Tonga', 'تونگا');
INSERT INTO `countries` VALUES (237, 'TO', 'TG', '.tg', 'Togo', 'رفتن');
INSERT INTO `countries` VALUES (238, 'TP', 'ST', '.st', 'Sao Tome and Principe', 'سائوتومه و پرنسیپه');
INSERT INTO `countries` VALUES (239, 'TS', 'TN', '.tn', 'Tunisia', 'تونس');
INSERT INTO `countries` VALUES (240, 'TT', 'TL', '.tl', 'East Timor', 'تیمور شرقی');
INSERT INTO `countries` VALUES (241, 'TU', 'TR', '.tr', 'Turkey', 'بوقلمون');
INSERT INTO `countries` VALUES (242, 'TV', 'TV', '.tv', 'Tuvalu', 'توووالو');
INSERT INTO `countries` VALUES (243, 'TW', 'TW', '.tw', 'Taiwan', 'تایوان');
INSERT INTO `countries` VALUES (244, 'TX', 'TM', '.tm', 'Turkmenistan', 'ترکمنستان');
INSERT INTO `countries` VALUES (245, 'TZ', 'TZ', '.tz', 'Tanzania, United Republic of', 'تانزانیا، جمهوری متحده');
INSERT INTO `countries` VALUES (246, 'UG', 'UG', '.ug', 'Uganda', 'اوگاندا');
INSERT INTO `countries` VALUES (247, 'UK', 'GB', '.uk', 'United Kingdom', 'انگلستان');
INSERT INTO `countries` VALUES (248, 'UP', 'UA', '.ua', 'Ukraine', 'اوکراین');
INSERT INTO `countries` VALUES (249, 'US', 'US', '.us', 'United States', 'ایالات متحده');
INSERT INTO `countries` VALUES (250, 'UV', 'BF', '.bf', 'Burkina Faso', 'بورکینافاسو');
INSERT INTO `countries` VALUES (251, 'UY', 'UY', '.uy', 'Uruguay', 'اروگوئه');
INSERT INTO `countries` VALUES (252, 'UZ', 'UZ', '.uz', 'Uzbekistan', 'ازبکستان');
INSERT INTO `countries` VALUES (253, 'VC', 'VC', '.vc', 'Saint Vincent and the Grenadines', 'سنت وینسنت و گرنادین');
INSERT INTO `countries` VALUES (254, 'VE', 'VE', '.ve', 'Venezuela', 'ونزوئلا');
INSERT INTO `countries` VALUES (255, 'VI', 'VG', '.vg', 'British Virgin Islands', 'جزایر ویرجین بریتانیا');
INSERT INTO `countries` VALUES (256, 'VM', 'VN', '.vn', 'Vietnam', 'ویتنام');
INSERT INTO `countries` VALUES (257, 'VQ', 'VI', '.vi', 'Virgin Islands (US)', 'جزایر ویرجین (ایالات متحده)');
INSERT INTO `countries` VALUES (258, 'VT', 'VA', '.va', 'Holy See (Vatican City)', 'مقدس (واتیکان)');
INSERT INTO `countries` VALUES (259, 'WA', 'NA', '.na', 'Namibia', 'نامیبیا');
INSERT INTO `countries` VALUES (260, 'WE', '-', '-', 'West Bank', 'بانک غرب');
INSERT INTO `countries` VALUES (261, 'WF', 'WF', '.wf', 'Wallis and Futuna', 'والیس و فوتونا');
INSERT INTO `countries` VALUES (262, 'WI', 'EH', '.eh', 'Western Sahara', 'صحرای غربی');
INSERT INTO `countries` VALUES (263, 'WQ', 'UM', '-', 'Wake Island', 'جزیره ویک');
INSERT INTO `countries` VALUES (264, 'WS', 'WS', '.ws', 'Samoa', 'ساموآ');
INSERT INTO `countries` VALUES (265, 'WZ', 'SZ', '.sz', 'Swaziland', 'سوازیلند');
INSERT INTO `countries` VALUES (266, 'YI', 'CS', '.yu', 'Serbia and Montenegro', 'صربستان و مونته نگرو');
INSERT INTO `countries` VALUES (267, 'YM', 'YE', '.ye', 'Yemen', 'یمن');
INSERT INTO `countries` VALUES (268, 'ZA', 'ZM', '.zm', 'Zambia', 'زامبیا');
INSERT INTO `countries` VALUES (269, 'ZI', 'ZW', '.zw', 'Zimbabwe', 'زیمبابوه');


